set_property IOSTANDARD LVCMOS33 [get_ports clk_out]
set_property PACKAGE_PIN A11 [get_ports clk_out]
set_property PACKAGE_PIN AA13 [get_ports rst_n]
set_property PACKAGE_PIN AB11 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]


set_property PACKAGE_PIN A11 [get_ports clk_out_4]
set_property PACKAGE_PIN A13 [get_ports clk_out_3]
set_property PACKAGE_PIN A14 [get_ports clk_out_2]
set_property PACKAGE_PIN E13 [get_ports clk_out_1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out_1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out_2]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out_3]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out_4]
