set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN W13 [get_ports led]
set_property PACKAGE_PIN AA13 [get_ports rst_n]
set_property PACKAGE_PIN AB11 [get_ports sys_clk]
